version: '2'
services:
  firefox:
    image: 'jess/firefox'
    container_name: 'firefox'
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    environment:
#      - DISPLAY=$DISPLAY_MAC
      - DISPLAY=unix$DISPLAY
